

service: serverless-sample


provider:
  name: aws
  runtime: python3.8
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb: DescribeTable
        - dynamodb: Query
        - dynamodb: Scan
        - dynamodb: GetItem
        - dynamodb: PutItem
        - dynamodb: UpdateItem
        - dynamodb: DeleteItem
      Resource:
        - {"Fn::GetAtt": ["CountryDynamoDBTable","Arn"]}
  


functions:
  hello:
    handler: handler.hello
    layers: 
      - arn:aws:lambda:ap-southeast-1:885930843522:layer:python-singapore-request:1
    events:
      - http:
          path: hello
          method: post
      - http:
          path: country/all
          method: get
      - http: 
          path: country/name/{country-name}
          method: get
      - http:
          path: country/capital/{capital-name}
          method: get
resources:
  Resources:
    CountryDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CountryTable
        AttributeDefinitions:
          - AttributeName: CountryId
            AttributeType:  S
        KeySchema:
          - AttributeName: CountryId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5


          


      
